// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArJ2wyq7oTwdifaxXd-3k9MNxzZMB3qB0',
    appId: '1:1026224257603:web:7dccb2e0db3f737ebef2f6',
    messagingSenderId: '1026224257603',
    projectId: 'naser-side-kick',
    authDomain: 'naser-side-kick.firebaseapp.com',
    storageBucket: 'naser-side-kick.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLi_RB8vj5H6XhTWzQZn8Gf5J4aEOyKc8',
    appId: '1:1026224257603:android:e8f2b5dc67943f5bbef2f6',
    messagingSenderId: '1026224257603',
    projectId: 'naser-side-kick',
    storageBucket: 'naser-side-kick.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYxT1wWuKzd-ttvBZvAx0Y8DyLWJPT5PI',
    appId: '1:1026224257603:ios:d6e83195da1e4af7bef2f6',
    messagingSenderId: '1026224257603',
    projectId: 'naser-side-kick',
    storageBucket: 'naser-side-kick.appspot.com',
    iosClientId: '1026224257603-vjhaskugeo017j24l2trpmk6ld5q97ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.interviewFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYxT1wWuKzd-ttvBZvAx0Y8DyLWJPT5PI',
    appId: '1:1026224257603:ios:d6e83195da1e4af7bef2f6',
    messagingSenderId: '1026224257603',
    projectId: 'naser-side-kick',
    storageBucket: 'naser-side-kick.appspot.com',
    iosClientId: '1026224257603-vjhaskugeo017j24l2trpmk6ld5q97ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.interviewFlutter',
  );
}
